apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: advisor-osc

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-hpa.yaml
  - network-policy.yaml
  - ingress.yaml

# 공통 라벨
commonLabels:
  project: advisor-osc
  managed-by: kustomize
